// <auto-generated />
namespace The_Ace_of_Spades_Pizza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ObjectFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ObjectFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150525597_ObjectFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
