// <auto-generated />
namespace The_Ace_of_Spades_Pizza.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150558292_SeedFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
